//! Human descriptions complement the protocol-derived command and field lists.
pub(super) fn summary(topic: &str) -> &'static str {
    match topic {
        "" => "Inspect your desktop, preview a plan, then apply and verify it.",
        "pane" => "Create, configure, resize, arrange and sort panes",
        "item" => "Assign, release and reorder desktop items",
        "folder" => "Manage mapped folders, navigation and content sizing",
        "search" => "Query Everything and browse asynchronous results",
        "tab" => "Merge, select, reorder and detach pane tabs",
        "plan" => "Preview changes and apply a validated plan",
        "request" => "Inspect receipts before retrying an uncertain change",
        "workspace" => "Read a complete workspace snapshot",
        "settings" => "Read and update supported app settings",
        "font" => "Discover available fonts",
        "startup" => "Inspect and configure Windows startup",
        "monitor" => "Discover monitor IDs and work areas",
        "skill" => "Export the bundled Agent guide offline",
        "status" => "Inspect the running app and desktop connection",
        "capabilities" => "Discover operations supported by the running app",
        "workspace.get" => "Read panes, items and the current concurrency context",
        "settings.get" => "Read supported application settings",
        "font.list" => "List available font candidates",
        "startup.get" => "Read the current Windows startup status",
        "monitor.list" => "List monitor IDs, work areas and DPI",
        "pane.list" => "List panes and their current state",
        "pane.get" => "Read one pane by ID",
        "folder.get" => "Read a folder pane's loaded snapshot and status",
        "search.get" => "Read a search pane's query, results and loading state",
        "item.list" => "List desktop items, optionally filtered by pane or unassigned status",
        "plan.preview" => "Validate a plan without saving; return its diff and apply token",
        "plan.apply" => "Apply a preview token; retain the request ID for recovery",
        "request.get" => "Read the receipt for an earlier request in this app instance",
        "pane.create" => "Create a desktop pane",
        "pane.update" => "Update pane title, locking, folding and display options",
        "pane.remove" => "Remove a pane; release its items only when explicitly requested",
        "pane.geometry" => "Set pane position and size in monitor-relative DIPs",
        "pane.fit" => "Fit pane content to an icon column count",
        "pane.snap" => "Snap beside another pane with a fixed 5-physical-pixel gap",
        "pane.arrange" => "Arrange panes into columns on a monitor",
        "pane.sort" => "Sort once by name, modified date, type or size; ascending unless descending=true",
        "item.assign" => "Assign desktop items to a pane",
        "item.release" => "Return assigned items to the desktop without moving files",
        "item.reorder" => "Set the complete item order in a desktop pane",
        "item.position" => "Position one existing pane member in a free grid cell or at content-relative DIP coordinates",
        "settings.update" => "Update settings from a plain JSON settings map",
        "tab.merge" => "Merge a pane into another pane's tab group",
        "tab.select" => "Select a tab by pane ID",
        "tab.reorder" => "Set a tab group's complete pane order",
        "tab.detach" => "Detach a tab into its own window",
        "folder.create" => "Create a pane mapped to a folder",
        "folder.update" => "Update folder mapping, view and sorting preferences",
        "folder.navigate" => "Navigate a folder pane to another directory",
        "folder.fit" => "Fit a loaded folder snapshot; list views preserve width",
        "folder.refresh" => "Request an asynchronous folder refresh without saving layout",
        "folder.back" => "Navigate to the previous folder",
        "folder.home" => "Return to the mapped home folder",
        "search.query" => "Submit a query to a search pane",
        "search.refresh" => "Refresh the current search query",
        "search.more" => "Load the next page of search results",
        "startup.set" => "Change startup only if its status matches the expected value",
        "schema" => "Print the bundled JSON Schema offline (raw schema, no response envelope)",
        "skill.show" => "Print the Skill entrypoint; --json exports all files for installation",
        _ => "",
    }
}

pub(super) fn examples(topic: &str, mutation: bool) -> Vec<String> {
    let command = topic.replace('.', " ");
    let args = match topic {
        "" => return ["help pane", "help pane snap", "capabilities --json", "workspace get --json"]
            .map(|s| format!("luciddesk-cli {s}")).into(),
        "pane.create" => "--title Work",
        "pane.update" => "--id 1 --locked true",
        "pane.remove" | "folder.back" | "folder.home" | "folder.refresh"
        | "search.refresh" | "search.more" | "tab.select" | "tab.detach" => "--id 1",
        "pane.sort" => "--id 1 --sort-column modified --descending true",
        "item.position" => "--pane 1 --item-id ITEM_A --column 2 --row 3",
        "pane.fit" => "--id 1 --icon-columns 6",
        "pane.snap" => "--id 1 --target 2 --side left --align start",
        "folder.fit" => "--id 1 --icon-columns 4 --max-rows 5",
        "folder.create" => "--title Projects --path C:\\Projects",
        "folder.update" => "--id 1 --list-view true",
        "folder.navigate" => "--id 1 --path C:\\Projects",
        "search.query" => "--id 1 --query *.pdf",
        "tab.merge" => "--id 1 --into 2",
        "item.assign" | "item.reorder" => "--id 1 --ids ITEM_A,ITEM_B",
        "item.release" => "--ids ITEM_A,ITEM_B",
        "pane.get" | "folder.get" | "search.get" => "--id 1",
        "item.list" => "--unassigned",
        "request.get" => "--id ORIGINAL_REQUEST_ID",
        "plan.preview" => "--input plan.json",
        "plan.apply" => "--token PREVIEW_TOKEN --request-id ORIGINAL_REQUEST_ID",
        "settings.update" => "--input settings.json",
        _ if mutation => "--input operation.json",
        _ => "",
    };
    vec![format!("luciddesk-cli {command}{}{} --json",
        if args.is_empty() { String::new() } else { format!(" {args}") },
        if mutation { " --dry-run" } else { "" })]
}
